### ISSUE TITLE
Error in parsing keysync when firing a weapon

### ISSUE THREAD

**Issue by NanoBob** [mta-slipe/Slipe-Server#125]
`[8-2-2021 23:46:51] [error]    Handling packet (PACKET_ID_PLAYER_KEYSYNC) failed.
Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
Actual value was 216.`

**Comment by NanoBob** [comment]
Seems to no longer happen after bullet sync config was changed. Might want to double check.
(Could have been accidentally fixed in the meantime since keysync has been changed a bit)

**Comment by CrosRoad95** [comment]
Maybe related to #241

**Comment by NanoBob** [comment]
> Maybe related to #241

Probably not, this bug has been there for a while before the packet pooling was implemented.

**Comment by NanoBob** [comment]
Unable to reproduce
