### ISSUE TITLE
Handling RpcPacket failed, index was out of range while joining the server

### ISSUE THREAD

**Issue by CrosRoad95** [mta-slipe/Slipe-Server#219]
![image](https://user-images.githubusercontent.com/22455534/131223166-de96f197-9f66-4bfd-adec-81dc5de462ae.png)
i tried to join the server and this happen.

After i tried to join again, i got this crash:
![image](https://user-images.githubusercontent.com/22455534/131223191-1afb15f9-9d42-4f13-823d-b8446736eb12.png)

**Comment by Zangomangu** [comment]
Getting the same error now, cant join
