### ISSUE TITLE
Look into replacement for certain statics

### ISSUE THREAD

**Issue by NanoBob** [mta-slipe/Slipe-Server#59]
Currently there are a couple statics in use in the project which could cause issues.

## Element create event
Currently the static `Created` event is triggered on every element in the constructor. Ideally we would know which `MtaServer` instance an element belongs to.

A potential solution would be offering an element factory to be dependency injected, and having that trigger the event.

This does have some implications towards creating new instances of elements (not being able to use a simple `new`). And this would impact inheriting from element classes as well. 

## Element ID generation
Currently element IDs are generated using an increment static `uint` on the `ElementIdGenerator` class. While for many uses this might be fine, this limits the library to only one range of element IDs per running application. Meaning multiple instances of `MtaServer` would share the same element ID range.

This also limits a user's ability to sync elements only to specific clients, and being able to re-use element ID ranges between different clients. This could be particularly useful for multi-gamemode servers. Where a client would only ever need to be aware of the elements from that gamemode.

This would likely require several different options for the assigning of element IDs.
If the above solution for element creation is implemented, then this factory could be in charge of assigning element IDs. Ideally it would have some configurable way to set how element IDs are assigned. It's important that this could potentially be `null` in case the user wants to manually assign IDs. It would be important to check whether or not an ID has been assigned before triggering the `created` event. Because this might (and probably will) send entity add packets to clients, resulting in errors if the IDs are undefined.

## Player join event
Currently the static event `OnJoin` (which should be renamed to `Joined` is triggered whenever a player joins the server. Just like with the element create event we would ideally be able to detect this on a per `MtaServer` basis.

A potential solution would be a `PlayerJoined` event on the `MtaServer` class, since instances of the `Player` class are always created as a result of a client connecting.

**Comment by msonnemans** [comment]
Having the `MtaServer` class as the primary conceptual object for events like `PlayerJoined`, `ElementCreated` etc. seems very intuitive. We should watch out that we aren't stacking these big conceptual instances, however. For example, MTA originally stacks "Server" upon "Core" upon "Game" etc. This should be avoided.
